#
# CONFIGURATION FOR BEACON WAYPOINTS
#

# The maximum amount of public waypoints that can exist at once on the server
max-public-waypoints: 100

# The maximum amount of private waypoints that each player can have
max-private-waypoints: 30

# Force waypoint names to be alphanumeric when they are created
force-alphanumeric-names: false

# The number of rows the public waypoint selection menu will show per page, not including the row for page navigation
# Range: 1-5
public-waypoint-menu-rows: 3

# The number of rows the private waypoint selection menu will show per page, not including the row for page navigation
# Range: 1-5
private-waypoint-menu-rows: 2

# Activate teleportation as soon as the destination is chosen without a warmup animation
instant-teleport: false

# Disable the particle animations when teleporting through a beacon
disable-animations: false

# Launch the player into the air when teleporting through a beacon
launch-player: true

# The y-level players will launch into the air before teleporting to the destination. Anti-cheat plugins may not allow
# players to go above a certain height, so adjust this as needed. The minimum value is the world height.
launch-player-height: 576

# By default, beacons teleport anyone standing on top of them. If you want to limit the teleportation to only the
# player who chooses the destination, set this to true.
disable-group-teleporting: false

# If the BeaconWaypoints.breakWaypointBeacons permission is disabled for a player, this will still allow them to break
# a beacon if all waypoints attached to it are owned by them. The owner of a beacon is the player who placed it.
allow-beacon-break-by-owner: true

# If you want to have players pay to teleport, you can change it here.
# The cost to teleport is determined by the amounts given here multiplied by the distance between the beacons in chunks.
# The value for each is only used when that mode is specified.
# If you want the cost to be the same at any distance, then set that value below
# and set cost-multiplier to 0.
# If a player is teleporting between dimensions, it will charge the dimension price.
# Money mode uses the currency from the EssentialsX plugin
# Modes: none, xp, money
payment-mode: none

xp-cost-per-chunk: 0
xp-cost-dimension: 0

money-cost-per-chunk: 0
money-cost-dimension: 0

# This value changes the cost of travel based on distance.
# The formula used is cost*(distance^multiplier), and the multiplier must be at least 0
# 0: constant cost for any distance
# Between 0 and 1: cost increases slower with distance
# 1: cost increases linearly
# Above 1: cost increases faster with distance
# This does not affect the price of teleporting between dimensions.
cost-multiplier: 0

# Require players to have a specific item with a specific name to teleport.
# If the item does not need a specific name (ex. custom items), then remove the "name" field.
# The amount of the item the player needs in their inventory can be set with the "amount" field.
# The amount of the item the player needs in their inventory to travel between dimensions can be set with the "amount-dimension" field.
# If you do not want the cost multiplier to affect item amounts needed, set "use-multiplier" to false.
# This could be useful if you require a certain amount of an item but also want an XP payment based on distance.
# You can set the item(s) to be consumed or let the player keep it with the "consume" field (ex. teleport spell item)
#
# Example for requiring either an ender pearl that is consumed and uses the cost multiplier
# or a gold nugget named "Teleport Token" with gold text that is not consumed and does not use the cost multiplier:
#
# required-items:
#   - item: ENDER_PEARL
#     amount: 1
#     dimension-amount: 10
#     use-multiplier: true
#     consume: true
#   - item: GOLD_NUGGET
#     name: ยง6Teleport Token
#     amount: 1
#     use-multiplier: false
#     consume: false
required-items:

# Prevent players from teleporting if they have certain items in their inventory
# Example:
# banned-items:
#   - SHULKER_BOX
#   - TNT
banned-items:

# Discovery mode will only show public waypoints that have been "discovered" by the player.
# A player discovers a waypoint by interacting with the beacon associated with it
discovery-mode: false

# Allow waypoints to be created in any world
allow-all-worlds: true

# List of worlds that allow waypoints if allow-all-worlds is disabled (based on folder name)
allowed-worlds:
  - world
  - world_nether
  - world_the_end

# List of items that can be used for waypoint icons
# The order given here is the same order that will be in the icon picker menu
waypoint-icons:
  - APPLE
  - SHROOMLIGHT
  - TOTEM_OF_UNDYING
  - EMERALD
  - DIAMOND
  - END_CRYSTAL
  - LEATHER
  - FILLED_MAP
  - SNOW_BLOCK
  - RED_MUSHROOM
  - CARROT
  - GOLDEN_APPLE
  - CREEPER_HEAD
  - PRISMARINE_BRICKS
  - ALLIUM
  - IRON_PICKAXE
  - QUARTZ_BRICKS
  - SKELETON_SKULL
  - POPPY
  - PUMPKIN
  - HONEYCOMB
  - SEA_LANTERN
  - BLUE_ICE
  - PURPUR_BLOCK
  - ENCHANTING_TABLE
  - OAK_LOG
  - WHEAT
  - RED_BED
  - ORANGE_TULIP
  - BLAZE_POWDER
  - SUGAR_CANE
  - LAPIS_LAZULI
  - CHORUS_FRUIT
  - END_PORTAL_FRAME
  - ELYTRA
  - BREWING_STAND
  - REDSTONE
  - RED_SAND
  - END_STONE
  - CACTUS
  - WATER_BUCKET
  - SHULKER_BOX
  - CHEST
  - NETHERITE_INGOT
  - SOUL_SAND
  - RED_NETHER_BRICKS
  - MAGMA_BLOCK
  - SAND
  - ENDER_PEARL
  - WARPED_STEM
  - CRIMSON_STEM
  - ZOMBIE_HEAD
  - OBSIDIAN
  - WITHER_SKELETON_SKULL
  - GRASS_BLOCK
  - IRON_BLOCK
  - COPPER_BLOCK
  - GOLD_BLOCK
  - DIAMOND_BLOCK
  - NETHERITE_BLOCK
  - SPRUCE_LOG
  - BIRCH_LOG
  - JUNGLE_LOG
  - ACACIA_LOG
  - DARK_OAK_LOG
  - SPONGE
  - BOOKSHELF
  - NETHERRACK
  - GLOWSTONE
  - STONE_BRICKS
  - DEEPSLATE_BRICKS
  - MELON
  - MYCELIUM
  - EMERALD_BLOCK
  - HAY_BLOCK
  - BAMBOO
  - IRON_BARS
  - DRAGON_HEAD
  - CAMPFIRE
  - BEE_NEST
  - TNT
  - BEACON
  - QUARTZ
  - IRON_INGOT
  - COPPER_INGOT
  - GOLD_INGOT
  - STRING
  - FEATHER
  - GUNPOWDER
  - WHEAT_SEEDS
  - BRICK
  - BOOK
  - SLIME_BALL
  - EGG
  - BONE
  - BLAZE_ROD
  - GOLD_NUGGET
  - NETHER_WART
  - ENDER_EYE
  - EXPERIENCE_BOTTLE
  - NETHER_STAR
  - FIREWORK_ROCKET
  - MUSIC_DISC_STAL
  - CAKE
  - SWEET_BERRIES
  - WHITE_WOOL
  - GOLDEN_PICKAXE
  - DIAMOND_PICKAXE
  - NETHERITE_PICKAXE
  - FISHING_ROD
  - TRIDENT
  - GOLDEN_CARROT